DROP TABLE IF EXISTS Cloths;
DROP TABLE IF EXISTS Sellers;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS User_Address;
DROP TABLE IF EXISTS Shopping_Carts;
DROP TABLE IF EXISTS Transactions;
DROP TABLE IF EXISTS Sizes;
DROP TABLE IF EXISTS Payments;
DROP TABLE IF EXISTS Feedback;

DROP TRIGGER IF EXISTS sellers_avg_price1;
DROP TRIGGER IF EXISTS sellers_avg_price2;
DROP TRIGGER IF EXISTS delete_cloth;
DROP TRIGGER IF EXISTS delete_seller;
DROP TRIGGER IF EXISTS delete_user;
DROP TRIGGER IF EXISTS sales_update;
DROP TRIGGER IF EXISTS sold_out;

DROP VIEW IF EXISTS other_user;
DROP VIEW IF EXISTS staff_user;
